### ISSUE TITLE
Icons fail to display

### ISSUE THREAD

**Issue by kassemsandarusi** [jesseweed/yeti-syntax#3]
Machine: Ubuntu 14.10 x86_64
Atom: v0.155, vanilla

Steps to bug:
1. Search 'Yeti' on atom theme.
2. Install Yeti.
3. Enable Yeti.
4. Atom resets with yeti-ui.

Icons are square boxes, definitely a problem within the icons.css. If I replace icons.css with seti-ui's icons.css icons do appear now; however, this causes problems with the UI.

**Comment by kassemsandarusi** [comment]
CRAP meant for yeti-ui

**Comment by jakeharris** [comment]
Actually, this is still an issue. I've installed Atom and yeti-ui on three different machines now, and each time, the icons are broken. I'm making a pull request as we speak.

**Comment by jakeharris** [comment]
...the previous comments confused me. I only just now realized my inability to read. Sorry. To the yeti-ui page!
